version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c 
      "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    depends_on:
      - db
      

  db:
    image: postgres
    ports:
      - "5432:5433"
    environment:
      - POSTGRES_DB=Cinema_DB
      - POSTGRES_USER=abwcbcui
      - POSTGRES_PASSWORD=d1o-YIjrqQEB0osq-m8VoLyIKbuxEElJ
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
